# Generated by Django 4.1.7 on 2023-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=15)),
                ('vehicleType', models.CharField(choices=[('Two', 'Two'), ('Three', 'Three'), ('Four wheelers', 'Four wheelers')], max_length=15)),
                ('vehicleModel', models.CharField(max_length=50)),
                ('vehicleDescription', models.TextField(max_length=500)),
            ],
        ),
    ]
